name: "Shortcut for Github Actions"
description: "Fetch story details from Shortcut"
author: "Epsy Engineering <engieering@epsyhealth.com>"

inputs:
  issue:
    description: Story or Epic ID
    required: true

outputs:
  title:
    description: Issue title
  type:
    description: Type of the issue
  subtype:
    description: Type of the story. For epic always epic
  description:
    description: Description
  slug:
    description: URL friendly name
  link:
    description: Shortcut link

runs:
  using: "docker"
  image: 'docker://epsyhealth/action-shortcut'
