name: "Shortcut for Github Actions"
description: "Fetch story details from Shortcut"
author: "Epsy Engineering <engieering@epsyhealth.com>"

inputs:
  issue:
    description: Story or Epic ID
    required: true
  soft_fail:
    description: Soft fail if unable to locate story
    required: false
    default: false

outputs:
  title:
    description: Issue title
  type:
    description: Type of the issue
  subtype:
    description: Type of the story. For epic always epic
  description:
    description: Description
  slug:
    description: URL friendly name
  link:
    description: Shortcut link
  pr_branch:
    description: Proposed name for fix branch
  pr_title:
    description: Proposed name for PR title

runs:
  using: "docker"
  image: 'docker://epsyhealth/action-shortcut'
